### ISSUE TITLE
Performance: Improve page rendering to 1sec

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#257]
![](https://cl.ly/3O2f3R010O32/Image%202018-03-30%20at%2019.36.44.public.png)

Ref: https://developers.google.com/web/tools/lighthouse/audits/first-interactive

**Comment by pftg** [comment]
@andriyParashchuk could you produce list of changes which we should do in order to achieve this? Some examples:

1. https://cl.ly/3G421b3I2w2O/Image%202018-04-17%20at%2016.09.34.public.png
2. https://cl.ly/280P1Z3I0K3Z/Image%202018-04-17%20at%2016.11.17.public.png

**Comment by andriyParashchuk** [comment]
- CSS rules
Remove unused rules from stylesheets to reduce unnecessary bytes consumed by network activity.
![image](https://user-images.githubusercontent.com/15202961/39081401-575cd076-4549-11e8-9e81-5a159e805b6c.png) 
[Learn more](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery)

- Prioritize visible content 
If the amount of data required exceeds the initial congestion window (typically 14.6kB compressed), it will require additional round trips between your server and the user’s browser. For users on networks with high latencies such as mobile networks this can cause significant delays to page loading.
![image](https://user-images.githubusercontent.com/15202961/39081146-cfabc050-4544-11e8-93cf-2a92189a7d2f.png)
To make pages load faster, limit the size of the data (HTML markup, images, CSS, JavaScript) that is needed to render the above-the-fold content of your page. There are several ways to do this:
1. [Structure your HTML to load the critical, above-the-fold content first](https://developers.google.com/speed/docs/insights/PrioritizeVisibleContent#structure)
1. [Reduce the amount of data used by your resources](https://developers.google.com/speed/docs/insights/PrioritizeVisibleContent#reduce)

- Offscreen images
Offscreen images are images that appear below the fold. Since users can't see offscreen images when they load a page, there's no reason to download the offscreen images as part of the initial page load. In other words, deferring the load of offscreen images can speed up page load time and time to interactive.
Recomendation: Consider lazy-loading offscreen images to improve page load speed and time to interactive. For more details see: [Lazy loading Images and Video](https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/).

- Serve images in next-gen formats
JPEG 2000, JPEG XR, and WebP are image formats that have superior compression and quality characteristics compared to their older JPEG and PNG counterparts. Encoding your images in these formats rather than JPEG or PNG means that they will load faster and consume less cellular data.
WebP is supported in Chrome and Opera and provides better lossy and lossless compression for images on the web. See [A New Image Format For The Web](https://developers.google.com/speed/webp/) for more on WebP.
![image](https://user-images.githubusercontent.com/15202961/39081364-cbf3957e-4548-11e8-9885-84c23c69170c.png)

- JavaScript boot-up time is too high
Check this out:
[JavaScript Start-up Optimization](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/javascript-startup-optimization/)
[Loading Third-Party JavaScript](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/)
![image](https://user-images.githubusercontent.com/15202961/39081944-2c8f5878-4553-11e8-9114-adc3689bb691.png)

- Enable compression
All modern browsers support and automatically negotiate gzip compression for all HTTP requests. Enabling gzip compression can reduce the size of the transferred response by up to 90%, which can significantly reduce the amount of time to download the resource, reduce data usage for the client, and improve the time to first render of your pages. See [text compression with GZIP](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer#text-compression-with-gzip) to learn more.
![image](https://user-images.githubusercontent.com/15202961/39081196-a65fe89c-4545-11e8-8321-17470a067d96.png)

- Eliminating Unnecessary Downloads
Inventory your own assets and third-party assets on your pages.
Measure the performance of each asset: its value and its technical performance.
Determine if the resources are providing sufficient value.
Eliminate it if it needed.

- Critical Request Chains
The Critical Request Chain is a concept from the Critical Rendering Path (CRP) optimization strategy. CRP enables the browser to load a page as quickly as possible by prioritizing which resources get loaded and the order in which they load.
![image](https://user-images.githubusercontent.com/15202961/39081906-702fe0bc-4552-11e8-84aa-637e6273140f.png)

**Comment by pftg** [comment]
Will be great to compare our structure with https://github.com/jetthoughts/jetthoughts.github.io/issues/281

**Comment by pftg** [comment]
- [x] Move GA to head
- [x] Delete hotjar https://dzwonsemrish7.cloudfront.net/items/1d1B3Y1A271q150e3Z0g/Image%202018-04-26%20at%2015.43.36.public.png

**Comment by pftg** [comment]
- [ ] https://cl.ly/3e0w410l3B0T/Image%202018-04-28%20at%2017.08.16.public.png

**Comment by pftg** [comment]
Reached goal, need to split left part and schedule it on later

**Comment by pftg** [comment]
@obliviusm please close this after you have verified all issues and move not fixed one into new one

**Comment by obliviusm** [comment]
ok. @sweatC is doing this

**Comment by sweatC** [comment]
This issue is closed because of following our Roadmap.
A list of tasks moved into https://github.com/jetthoughts/jetthoughts.github.io/issues/302 and plan to be done in the next iteration.
