### ISSUE TITLE
SEO: Tools

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#264]
We should support

* Indexing by: Google Search, Bing Search, DuckDuck Search
* Search Result View: Google Search, Bing Search, DuckDuck Search
* Social Sharing Metadata: Facebook, Twitter

Analyze:

1. https://neilpatel.com/seo-analyzer/analyze/
2. http://tools.neilpatel.com/en/analyze/https%3A%2F%2Fwww.jetthoughts.com%2F
3. https://blog.hubspot.com/marketing/seo-analysis-tools

https://developers.facebook.com/tools/debug/og/object/ => ![](https://cl.ly/080u2d3g1W0P/Image%202018-05-10%20at%2017.09.13.public.png)

**Comment by andriyParashchuk** [comment]
Learn more: https://webmasters.googleblog.com/2008/10/importance-of-link-architecture.html
![kazam_screenshot_00000](https://user-images.githubusercontent.com/15202961/39751958-9dc250a0-52c2-11e8-994b-94ad58ce778e.png)
Learn more: https://developers.google.com/web/fundamentals/design-and-ux/responsive/#optimize_text_for_reading
![kazam_screenshot_00002](https://user-images.githubusercontent.com/15202961/39752012-cf6f01c0-52c2-11e8-9f5f-dd75158f7237.png)


![1525800702430](https://user-images.githubusercontent.com/23320186/39772808-db5b615e-52fe-11e8-82a0-5dc16e1c9f95.jpg)
![1525800648727](https://user-images.githubusercontent.com/23320186/39772809-db783fc2-52fe-11e8-8cac-10071ee0e547.jpg)
![1525800638498](https://user-images.githubusercontent.com/23320186/39772810-db990a40-52fe-11e8-9013-71ef49cb8109.jpg)

**Comment by pftg** [comment]
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.jetthoughts.com

**Comment by pftg** [comment]
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

**Comment by pftg** [comment]
https://moz.com/blog/meta-data-templates-123

**Comment by pftg** [comment]
- [ ] https://cl.ly/0e2R1b1m1R35/Image%202018-05-12%20at%2020.09.12.public.png
- [ ] https://cl.ly/130C3k203h2U/Image%202018-05-12%20at%2020.10.06.public.png
- [ ] https://cl.ly/130C3k203h2U/Image%202018-05-12%20at%2020.10.06.public.png

**Comment by obliviusm** [comment]
Done in #319 #310 #301 #309 #308 #259

Next SEO issues are connected with epic #326
