### ISSUE TITLE
Meta tags

### ISSUE THREAD

**Issue by mir4a** [jetthoughts/jt.github.io#8]
- [x] Open graph tags http://ogp.me/
- [x] Twitter cards https://dev.twitter.com/cards
- [x] Need to register app and insert app id into meta tag
- [x] After production deployment need to validate and send application for twitter cards. More info at https://dev.twitter.com/docs/cards/validation/validator
